name: Cryptic Backend Docs Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Docs with Gradle
        run: ./gradlew aggregateJavadoc createDocs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/docs/javadoc
          DEBUG: false
          TARGET_FOLDER: javadoc/latest
          CLEAN: true
          CLEAN_EXCLUDE: '["LICENSE", "daemon-api", "api", "README.md", "_config.yml", "deployment.md", "getting-started.md", "index.md", "license.md"]'
          GIT_CONFIG_NAME: GitHub Actions
          GIT_CONFIG_EMAIL: actions@github.com

