name: Cryptic Backend Sentry
on:
  push: #Todo: After fixing Sentry reactivate this action
    branches-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SENTRY_URL: https://sentry.the-morpheus.de/
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: cryptic
      SENTRY_PROJECT: java-backend
      SENTRY_LOG_LEVEL: INFO
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Setup Sentry CLI
        run: curl -sL https://sentry.io/get-cli/ | bash
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Sentry Development
        if: github.ref == 'refs/heads/experimental'
        env:
          SENTRY_DEPLOY_ENVIRONMENT: development
        run: |
          export SENTRY_RELEASE=$(./gradlew version | grep Version | cut -c9-)
          sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
          sentry-cli releases set-commits --auto $SENTRY_RELEASE
          sentry-cli releases finalize $SENTRY_RELEASE
          sentry-cli releases deploys $SENTRY_RELEASE new -e $SENTRY_DEPLOY_ENVIRONMENT
      - name: Sentry Production
        if: github.ref == 'refs/heads/master'
        env:
          SENTRY_DEPLOY_ENVIRONMENT: production
        run: |
          export SENTRY_RELEASE=$(./gradlew version | grep Version | cut -c9-)
          sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
          sentry-cli releases set-commits --auto $SENTRY_RELEASE
          sentry-cli releases finalize $SENTRY_RELEASE
